version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: docker/prod/node/Dockerfile
    image: api
    restart: on-failure
    container_name: api
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    networks:
      - backend
    stdin_open: true
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
